import { useState, useEffect, type ReactElement } from 'react'
import Editor from '@monaco-editor/react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription } from '@/components/ui/alert'

interface FileNode {
  name: string
  path: string
  type: 'file' | 'folder'
  children?: FileNode[]
}

interface MonacoCodeEditorProps {
  files: string[]
  projectId: string
}

export function MonacoCodeEditor({ files, projectId }: MonacoCodeEditorProps) {
  const [fileTree, setFileTree] = useState<FileNode[]>([])
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [fileContent, setFileContent] = useState<string>('')
  const [isModified, setIsModified] = useState(false)
  const [theme, setTheme] = useState<'vs-dark' | 'light'>('vs-dark')

  useEffect(() => {
    // Build file tree from flat file list
    const tree = buildFileTree(files)
    setFileTree(tree)
    
    // Select first file by default
    if (files.length > 0) {
      handleFileSelect(files[0])
    }
  }, [files])

  const buildFileTree = (filePaths: string[]): FileNode[] => {
    const root: FileNode[] = []
    
    filePaths.forEach(filePath => {
      const parts = filePath.split('/')
      let currentLevel = root
      
      parts.forEach((part, index) => {
        const isFile = index === parts.length - 1
        const existingNode = currentLevel.find(node => node.name === part)
        
        if (existingNode) {
          if (!isFile && existingNode.children) {
            currentLevel = existingNode.children
          }
        } else {
          const newNode: FileNode = {
            name: part,
            path: parts.slice(0, index + 1).join('/'),
            type: isFile ? 'file' : 'folder',
            children: isFile ? undefined : []
          }
          currentLevel.push(newNode)
          if (!isFile && newNode.children) {
            currentLevel = newNode.children
          }
        }
      })
    })
    
    return root
  }

  const handleFileSelect = (filePath: string) => {
    setSelectedFile(filePath)
    setIsModified(false)
    loadFileContent(filePath)
  }

  const loadFileContent = (filePath: string) => {
    const fileName = filePath.split('/').pop() || ''
    const fileExt = fileName.split('.').pop()
    
    let content = ''
    
    switch (fileExt) {
      case 'py':
        content = `# ${fileName}
# Generated by MetaMind - Autonomous AI Pipeline Designer

from typing import List, Dict, Any, Optional
import os
from dotenv import load_dotenv
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

class RAGPipeline:
    """
    Retrieval-Augmented Generation Pipeline
    
    This pipeline implements a complete RAG system with:
    - Document ingestion and chunking
    - Vector embedding generation
    - Similarity search
    - LLM-based response generation
    - Source attribution
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gpt-4",
        embedding_model: str = "text-embedding-ada-002"
    ):
        """
        Initialize the RAG pipeline
        
        Args:
            api_key: OpenAI API key (defaults to env variable)
            model: LLM model to use
            embedding_model: Embedding model for vector generation
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model
        self.embedding_model = embedding_model
        self.vector_store = None
        
        logger.info(f"Initialized RAG Pipeline with model: {model}")
        
    def ingest_documents(self, documents: List[str]) -> None:
        """
        Ingest and process documents into the vector store
        
        Args:
            documents: List of document texts to ingest
        """
        logger.info(f"Ingesting {len(documents)} documents")
        # Implementation here
        pass
        
    def query(
        self,
        query: str,
        top_k: int = 5,
        temperature: float = 0.7
    ) -> Dict[str, Any]:
        """
        Process a query through the RAG pipeline
        
        Args:
            query: User query string
            top_k: Number of relevant documents to retrieve
            temperature: LLM temperature for response generation
            
        Returns:
            Dictionary containing:
                - response: Generated response text
                - sources: List of source documents used
                - confidence: Confidence score (0-1)
                - metadata: Additional metadata
        """
        logger.info(f"Processing query: {query[:50]}...")
        
        # 1. Retrieve relevant documents
        relevant_docs = self._retrieve_documents(query, top_k)
        
        # 2. Generate response using LLM
        response = self._generate_response(query, relevant_docs, temperature)
        
        # 3. Calculate confidence score
        confidence = self._calculate_confidence(response, relevant_docs)
        
        return {
            "response": response,
            "sources": relevant_docs,
            "confidence": confidence,
            "metadata": {
                "model": self.model,
                "top_k": top_k,
                "temperature": temperature
            }
        }
    
    def _retrieve_documents(self, query: str, top_k: int) -> List[Dict[str, Any]]:
        """Retrieve relevant documents from vector store"""
        # Implementation here
        return []
    
    def _generate_response(
        self,
        query: str,
        context: List[Dict[str, Any]],
        temperature: float
    ) -> str:
        """Generate response using LLM with retrieved context"""
        # Implementation here
        return "Generated response"
    
    def _calculate_confidence(
        self,
        response: str,
        sources: List[Dict[str, Any]]
    ) -> float:
        """Calculate confidence score for the response"""
        # Implementation here
        return 0.95

def main():
    """Main entry point"""
    pipeline = RAGPipeline()
    
    # Example usage
    result = pipeline.query("What is machine learning?")
    
    print(f"Response: {result['response']}")
    print(f"Confidence: {result['confidence']:.2%}")
    print(f"Sources: {len(result['sources'])}")

if __name__ == "__main__":
    main()
`
        break
        
      case 'txt':
        if (fileName === 'requirements.txt') {
          content = `# Python Dependencies
# Generated by MetaMind

# Core Framework
fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
python-dotenv==1.0.0

# AI/ML Libraries
langchain==0.1.0
openai==1.3.0
tiktoken==0.5.1

# Vector Database
chromadb==0.4.18
sentence-transformers==2.2.2

# Data Processing
numpy==1.24.3
pandas==2.1.3

# Utilities
python-multipart==0.0.6
aiofiles==23.2.1
httpx==0.25.2

# Development
pytest==7.4.3
black==23.12.0
flake8==6.1.0
mypy==1.7.1
`
        }
        break
        
      case 'md':
        content = `# ${projectId}

## 🚀 Overview

This project was generated by **MetaMind** - an Autonomous AI Pipeline Designer & Optimizer.

MetaMind uses advanced AI reasoning to design, optimize, and generate production-ready AI pipelines tailored to your specific requirements.

## ✨ Features

- ✅ **Retrieval-Augmented Generation (RAG)** - Advanced document retrieval and response generation
- ✅ **Vector Database Integration** - ChromaDB for efficient similarity search
- ✅ **RESTful API** - FastAPI-based endpoints for easy integration
- ✅ **Docker Support** - Containerized deployment ready
- ✅ **Environment Configuration** - Flexible configuration management
- ✅ **Logging & Monitoring** - Built-in logging for debugging and monitoring

## 📋 Prerequisites

- Python 3.9 or higher
- Docker and Docker Compose (optional, for containerized deployment)
- OpenAI API key

## 🔧 Installation

### Local Development

1. **Clone or extract the project**

2. **Create a virtual environment**
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   \`\`\`

3. **Install dependencies**
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

4. **Set up environment variables**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your API keys and configuration
   \`\`\`

5. **Run the application**
   \`\`\`bash
   python main.py
   \`\`\`

### Docker Deployment

1. **Build and run with Docker Compose**
   \`\`\`bash
   docker-compose up -d
   \`\`\`

2. **View logs**
   \`\`\`bash
   docker-compose logs -f
   \`\`\`

3. **Stop the application**
   \`\`\`bash
   docker-compose down
   \`\`\`

## 🌐 API Documentation

Once running, access the interactive API documentation:

- **Swagger UI**: http://localhost:8000/docs
- **ReDoc**: http://localhost:8000/redoc
- **Health Check**: http://localhost:8000/health

## 📚 Usage Examples

### Python Client

\`\`\`python
import requests

# Query the RAG pipeline
response = requests.post(
    "http://localhost:8000/query",
    json={
        "query": "What is machine learning?",
        "top_k": 5,
        "temperature": 0.7
    }
)

result = response.json()
print(f"Response: {result['response']}")
print(f"Confidence: {result['confidence']}")
\`\`\`

### cURL

\`\`\`bash
curl -X POST "http://localhost:8000/query" \\
  -H "Content-Type: application/json" \\
  -d '{
    "query": "What is machine learning?",
    "top_k": 5,
    "temperature": 0.7
  }'
\`\`\`

## 🏗️ Architecture

This RAG pipeline includes:

1. **Document Ingestion** - Process and chunk documents
2. **Vector Embedding** - Generate embeddings using OpenAI
3. **Vector Storage** - Store in ChromaDB for fast retrieval
4. **Similarity Search** - Find relevant documents
5. **Response Generation** - Generate contextual responses using LLM
6. **Source Attribution** - Track and return source documents

## ⚙️ Configuration

Edit the \`.env\` file to configure:

\`\`\`env
# API Configuration
OPENAI_API_KEY=your_api_key_here
MODEL=gpt-4
EMBEDDING_MODEL=text-embedding-ada-002

# Database Configuration
CHROMA_HOST=localhost
CHROMA_PORT=8001

# Application Settings
DEBUG=false
LOG_LEVEL=info
MAX_TOKENS=2000
TEMPERATURE=0.7
TOP_K=5
\`\`\`

## 🧪 Testing

Run the test suite:

\`\`\`bash
pytest tests/
\`\`\`

## 📊 Monitoring

The application includes built-in logging. View logs:

\`\`\`bash
# Local
tail -f logs/app.log

# Docker
docker-compose logs -f app
\`\`\`

## 🤝 Contributing

This project was generated by MetaMind. To modify:

1. Edit the source files as needed
2. Run tests to ensure functionality
3. Update documentation if adding features

## 📄 License

MIT License

## 🙏 Acknowledgments

- Generated by **MetaMind** - Autonomous AI Pipeline Designer
- Powered by OpenAI GPT-4
- Built with FastAPI and LangChain

## 📞 Support

For issues or questions about MetaMind, please refer to the MetaMind documentation.

---

**Generated by MetaMind** - Turning requirements into production-ready AI systems.
`
        break
        
      case 'yml':
      case 'yaml':
        content = `version: '3.8'

services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-pipeline
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=\${OPENAI_API_KEY}
      - MODEL=\${MODEL:-gpt-4}
      - EMBEDDING_MODEL=\${EMBEDDING_MODEL:-text-embedding-ada-002}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - DEBUG=\${DEBUG:-false}
      - LOG_LEVEL=\${LOG_LEVEL:-info}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - chromadb
    restart: unless-stopped
    networks:
      - rag-network
    
  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  chroma-data:
    driver: local

networks:
  rag-network:
    driver: bridge
`
        break
        
      case 'env':
        content = `# Environment Configuration
# Generated by MetaMind

# ======================
# API Configuration
# ======================
OPENAI_API_KEY=your_openai_api_key_here
MODEL=gpt-4
EMBEDDING_MODEL=text-embedding-ada-002

# ======================
# Database Configuration
# ======================
CHROMA_HOST=localhost
CHROMA_PORT=8001
CHROMA_COLLECTION=documents

# ======================
# Application Settings
# ======================
DEBUG=false
LOG_LEVEL=info
HOST=0.0.0.0
PORT=8000

# ======================
# RAG Pipeline Settings
# ======================
MAX_TOKENS=2000
TEMPERATURE=0.7
TOP_K=5
CHUNK_SIZE=1000
CHUNK_OVERLAP=200

# ======================
# Performance Settings
# ======================
MAX_WORKERS=4
TIMEOUT=30
RATE_LIMIT=100

# ======================
# Security Settings
# ======================
CORS_ORIGINS=http://localhost:3000,http://localhost:3001
API_KEY_HEADER=X-API-Key
`
        break
        
      default:
        content = `# ${fileName}

This file was generated by MetaMind.

File content will be populated based on your architecture design.
`
    }
    
    setFileContent(content)
  }

  const handleEditorChange = (value: string | undefined) => {
    if (value !== undefined) {
      setFileContent(value)
      setIsModified(true)
    }
  }

  const handleSave = () => {
    console.log('Saving file:', selectedFile)
    console.log('Content length:', fileContent.length)
    // TODO: Implement actual save to backend
    setIsModified(false)
    alert('File saved successfully! (Note: This is a demo - actual backend integration needed)')
  }

  const getLanguage = (filePath: string): string => {
    const ext = filePath.split('.').pop()?.toLowerCase()
    const languageMap: Record<string, string> = {
      'py': 'python',
      'js': 'javascript',
      'ts': 'typescript',
      'jsx': 'javascript',
      'tsx': 'typescript',
      'json': 'json',
      'md': 'markdown',
      'yml': 'yaml',
      'yaml': 'yaml',
      'txt': 'plaintext',
      'env': 'plaintext',
      'sh': 'shell',
      'bash': 'shell',
      'dockerfile': 'dockerfile',
    }
    return languageMap[ext || ''] || 'plaintext'
  }

  const renderFileTree = (nodes: FileNode[], level: number = 0): ReactElement[] => {
    return nodes.map((node, index) => (
      <div key={node.path} style={{ marginLeft: `${level * 16}px` }}>
        {node.type === 'folder' ? (
          <div>
            <div className="flex items-center gap-2 py-1 px-2 hover:bg-muted rounded cursor-pointer">
              <span>📁</span>
              <span className="text-sm font-medium">{node.name}</span>
            </div>
            {node.children && renderFileTree(node.children, level + 1)}
          </div>
        ) : (
          <div
            className={`flex items-center gap-2 py-1 px-2 rounded cursor-pointer transition-colors ${
              selectedFile === node.path
                ? 'bg-primary text-primary-foreground'
                : 'hover:bg-muted'
            }`}
            onClick={() => handleFileSelect(node.path)}
          >
            <span>{getFileIcon(node.name)}</span>
            <span className="text-sm">{node.name}</span>
          </div>
        )}
      </div>
    ))
  }

  const getFileIcon = (fileName: string): string => {
    const ext = fileName.split('.').pop()?.toLowerCase()
    const iconMap: Record<string, string> = {
      'py': '🐍',
      'js': '📜',
      'ts': '📘',
      'json': '📋',
      'md': '📝',
      'yml': '⚙️',
      'yaml': '⚙️',
      'txt': '📄',
      'env': '🔐',
      'sh': '🔧',
      'dockerfile': '🐳',
    }
    return iconMap[ext || ''] || '📄'
  }

  return (
    <div className="grid grid-cols-12 gap-4 h-[800px]">
      {/* File Tree Sidebar */}
      <Card className="col-span-3 border-2 shadow-lg overflow-hidden flex flex-col">
        <CardHeader className="bg-gradient-to-r from-primary/10 to-primary/5 border-b pb-3">
          <CardTitle className="text-lg">📁 Project Files</CardTitle>
        </CardHeader>
        <CardContent className="flex-1 overflow-y-auto pt-4">
          {fileTree.length > 0 ? (
            <div className="space-y-1">
              {renderFileTree(fileTree)}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No files available</p>
          )}
        </CardContent>
      </Card>

      {/* Monaco Editor */}
      <Card className="col-span-9 border-2 shadow-lg overflow-hidden flex flex-col">
        <CardHeader className="bg-gradient-to-r from-primary/10 to-primary/5 border-b pb-3">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-lg">
                {selectedFile ? (
                  <span className="flex items-center gap-2">
                    {getFileIcon(selectedFile.split('/').pop() || '')}
                    {selectedFile.split('/').pop()}
                    {isModified && <span className="text-warning">●</span>}
                  </span>
                ) : (
                  'Select a file to edit'
                )}
              </CardTitle>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setTheme(theme === 'vs-dark' ? 'light' : 'vs-dark')}
              >
                {theme === 'vs-dark' ? '☀️' : '🌙'}
              </Button>
              {selectedFile && (
                <>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      navigator.clipboard.writeText(fileContent)
                      alert('Copied to clipboard!')
                    }}
                  >
                    📋 Copy
                  </Button>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleSave}
                    disabled={!isModified}
                  >
                    💾 Save
                  </Button>
                </>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent className="flex-1 p-0 overflow-hidden">
          {selectedFile ? (
            <Editor
              height="100%"
              language={getLanguage(selectedFile)}
              value={fileContent}
              onChange={handleEditorChange}
              theme={theme}
              options={{
                minimap: { enabled: true },
                fontSize: 14,
                lineNumbers: 'on',
                rulers: [80, 120],
                wordWrap: 'on',
                scrollBeyondLastLine: false,
                automaticLayout: true,
                tabSize: 4,
                insertSpaces: true,
                formatOnPaste: true,
                formatOnType: true,
              }}
            />
          ) : (
            <div className="flex items-center justify-center h-full">
              <Alert className="max-w-md">
                <AlertDescription className="text-center">
                  <p className="text-lg mb-2">👈 Select a file from the tree to start editing</p>
                  <p className="text-sm text-muted-foreground">
                    Full VS Code-like editing experience with syntax highlighting
                  </p>
                </AlertDescription>
              </Alert>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

// Made with Bob
