import { useState, useEffect, type ReactElement } from 'react'
import Editor from '@monaco-editor/react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription } from '@/components/ui/alert'

interface FileNode {
  name: string
  path: string
  type: 'file' | 'folder'
  children?: FileNode[]
}

interface MonacoCodeEditorProps {
  files: string[]
  projectId: string
}

export function MonacoCodeEditor({ files, projectId }: MonacoCodeEditorProps) {
  const [fileTree, setFileTree] = useState<FileNode[]>([])
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [fileContent, setFileContent] = useState<string>('')
  const [isModified, setIsModified] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [theme, setTheme] = useState<'vs-dark' | 'light'>('vs-dark')

  useEffect(() => {
    // Build file tree from flat file list
    const tree = buildFileTree(files)
    setFileTree(tree)
    
    // Select first file by default
    if (files.length > 0) {
      handleFileSelect(files[0])
    }
  }, [files])

  const buildFileTree = (filePaths: string[]): FileNode[] => {
    const root: FileNode[] = []
    
    filePaths.forEach(filePath => {
      const parts = filePath.split('/')
      let currentLevel = root
      
      parts.forEach((part, index) => {
        const isFile = index === parts.length - 1
        const existingNode = currentLevel.find(node => node.name === part)
        
        if (existingNode) {
          if (!isFile && existingNode.children) {
            currentLevel = existingNode.children
          }
        } else {
          const newNode: FileNode = {
            name: part,
            path: parts.slice(0, index + 1).join('/'),
            type: isFile ? 'file' : 'folder',
            children: isFile ? undefined : []
          }
          currentLevel.push(newNode)
          if (!isFile && newNode.children) {
            currentLevel = newNode.children
          }
        }
      })
    })
    
    return root
  }

  const handleFileSelect = (filePath: string) => {
    setSelectedFile(filePath)
    setIsModified(false)
    loadFileContent(filePath)
  }

  const loadFileContent = async (filePath: string) => {
    setIsLoading(true)
    try {
      // Fetch actual file content from backend
      const response = await fetch(
        `/api/code-editor/${projectId}/file?file_path=${encodeURIComponent(filePath)}`
      )
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }
      
      const data = await response.json()
      setFileContent(data.content)
    } catch (error) {
      console.error('Failed to load file content:', error)
      
      // Fallback to template content if API fails (maintains backward compatibility)
      const fileName = filePath.split('/').pop() || ''
      const fileExt = fileName.split('.').pop()
      
      let content = ''
      
      switch (fileExt) {
        case 'py':
          content = `# ${fileName}
# Generated by MetaMind - Autonomous AI Pipeline Designer

# Error loading file from backend
# Using template content as fallback

from typing import List, Dict, Any, Optional
import os
from dotenv import load_dotenv
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

class RAGPipeline:
    """
    Retrieval-Augmented Generation Pipeline
    
    This pipeline implements a complete RAG system with:
    - Document ingestion and chunking
    - Vector embedding generation
    - Similarity search
    - LLM-based response generation
    - Source attribution
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gpt-4",
        embedding_model: str = "text-embedding-ada-002"
    ):
        """
        Initialize the RAG pipeline
        
        Args:
            api_key: OpenAI API key (defaults to env variable)
            model: LLM model to use
            embedding_model: Embedding model for vector generation
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model
        self.embedding_model = embedding_model
        self.vector_store = None
        
        logger.info(f"Initialized RAG Pipeline with model: {model}")

def main():
    """Main entry point"""
    pipeline = RAGPipeline()
    print("RAG Pipeline initialized")

if __name__ == "__main__":
    main()
`
          break
          
        case 'txt':
          if (fileName === 'requirements.txt') {
            content = `# Python Dependencies
# Generated by MetaMind

# Error loading file from backend - using template

# Core Framework
fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
python-dotenv==1.0.0

# AI/ML Libraries
langchain==0.1.0
openai==1.3.0
tiktoken==0.5.1
`
          } else {
            content = `# ${fileName}

Error loading file content from backend.
Please check your connection and try again.
`
          }
          break
          
        case 'md':
          content = `# ${fileName}

## Error Loading File

Unable to load file content from backend.
Using template content as fallback.

This file was generated by **MetaMind** - an Autonomous AI Pipeline Designer & Optimizer.
`
          break
          
        case 'yml':
        case 'yaml':
          content = `# ${fileName}
# Error loading file from backend - using template

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
`
          break
          
        case 'env':
          content = `# Environment Configuration
# Generated by MetaMind

# Error loading file from backend - using template

# API Configuration
OPENAI_API_KEY=your_openai_api_key_here
MODEL=gpt-4
`
          break
          
        default:
          content = `# ${fileName}

Error loading file content from backend.
Please check your connection and try again.

This file was generated by MetaMind.
`
      }
      
      setFileContent(content)
    } finally {
      setIsLoading(false)
    }
  }

  const handleEditorChange = (value: string | undefined) => {
    if (value !== undefined) {
      setFileContent(value)
      setIsModified(true)
    }
  }

  const handleSave = () => {
    console.log('Saving file:', selectedFile)
    console.log('Content length:', fileContent.length)
    // TODO: Implement actual save to backend
    setIsModified(false)
    alert('File saved successfully! (Note: This is a demo - actual backend integration needed)')
  }

  const getLanguage = (filePath: string): string => {
    const ext = filePath.split('.').pop()?.toLowerCase()
    const languageMap: Record<string, string> = {
      'py': 'python',
      'js': 'javascript',
      'ts': 'typescript',
      'jsx': 'javascript',
      'tsx': 'typescript',
      'json': 'json',
      'md': 'markdown',
      'yml': 'yaml',
      'yaml': 'yaml',
      'txt': 'plaintext',
      'env': 'plaintext',
      'sh': 'shell',
      'bash': 'shell',
      'dockerfile': 'dockerfile',
    }
    return languageMap[ext || ''] || 'plaintext'
  }

  const renderFileTree = (nodes: FileNode[], level: number = 0): ReactElement[] => {
    return nodes.map((node) => (
      <div key={node.path} style={{ marginLeft: `${level * 16}px` }}>
        {node.type === 'folder' ? (
          <div>
            <div className="flex items-center gap-2 py-1 px-2 hover:bg-muted rounded cursor-pointer">
              <span>📁</span>
              <span className="text-sm font-medium">{node.name}</span>
            </div>
            {node.children && renderFileTree(node.children, level + 1)}
          </div>
        ) : (
          <div
            className={`flex items-center gap-2 py-1 px-2 rounded cursor-pointer transition-colors ${
              selectedFile === node.path
                ? 'bg-primary text-primary-foreground'
                : 'hover:bg-muted'
            }`}
            onClick={() => handleFileSelect(node.path)}
          >
            <span>{getFileIcon(node.name)}</span>
            <span className="text-sm">{node.name}</span>
          </div>
        )}
      </div>
    ))
  }

  const getFileIcon = (fileName: string): string => {
    const ext = fileName.split('.').pop()?.toLowerCase()
    const iconMap: Record<string, string> = {
      'py': '🐍',
      'js': '📜',
      'ts': '📘',
      'json': '📋',
      'md': '📝',
      'yml': '⚙️',
      'yaml': '⚙️',
      'txt': '📄',
      'env': '🔐',
      'sh': '🔧',
      'dockerfile': '🐳',
    }
    return iconMap[ext || ''] || '📄'
  }

  return (
    <div className="grid grid-cols-12 gap-4 h-[800px]">
      {/* File Tree Sidebar */}
      <Card className="col-span-3 border-2 shadow-lg overflow-hidden flex flex-col">
        <CardHeader className="bg-gradient-to-r from-primary/10 to-primary/5 border-b pb-3">
          <CardTitle className="text-lg">📁 Project Files</CardTitle>
        </CardHeader>
        <CardContent className="flex-1 overflow-y-auto pt-4">
          {fileTree.length > 0 ? (
            <div className="space-y-1">
              {renderFileTree(fileTree)}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No files available</p>
          )}
        </CardContent>
      </Card>

      {/* Monaco Editor */}
      <Card className="col-span-9 border-2 shadow-lg overflow-hidden flex flex-col">
        <CardHeader className="bg-gradient-to-r from-primary/10 to-primary/5 border-b pb-3">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-lg">
                {selectedFile ? (
                  <span className="flex items-center gap-2">
                    {getFileIcon(selectedFile.split('/').pop() || '')}
                    {selectedFile.split('/').pop()}
                    {isModified && <span className="text-warning">●</span>}
                  </span>
                ) : (
                  'Select a file to edit'
                )}
              </CardTitle>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setTheme(theme === 'vs-dark' ? 'light' : 'vs-dark')}
              >
                {theme === 'vs-dark' ? '☀️' : '🌙'}
              </Button>
              {selectedFile && (
                <>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      navigator.clipboard.writeText(fileContent)
                      alert('Copied to clipboard!')
                    }}
                  >
                    📋 Copy
                  </Button>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleSave}
                    disabled={!isModified}
                  >
                    💾 Save
                  </Button>
                </>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent className="flex-1 p-0 overflow-hidden">
          {selectedFile ? (
            isLoading ? (
              <div className="flex items-center justify-center h-full">
                <div className="text-center">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
                  <p className="text-muted-foreground">Loading file content...</p>
                </div>
              </div>
            ) : (
              <Editor
                height="100%"
                language={getLanguage(selectedFile)}
                value={fileContent}
                onChange={handleEditorChange}
                theme={theme}
                options={{
                  minimap: { enabled: true },
                  fontSize: 14,
                  lineNumbers: 'on',
                  rulers: [80, 120],
                  wordWrap: 'on',
                  scrollBeyondLastLine: false,
                  automaticLayout: true,
                  tabSize: 4,
                  insertSpaces: true,
                  formatOnPaste: true,
                  formatOnType: true,
                }}
              />
            )
          ) : (
            <div className="flex items-center justify-center h-full">
              <Alert className="max-w-md">
                <AlertDescription className="text-center">
                  <p className="text-lg mb-2">👈 Select a file from the tree to start editing</p>
                  <p className="text-sm text-muted-foreground">
                    Full VS Code-like editing experience with syntax highlighting
                  </p>
                </AlertDescription>
              </Alert>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
