"""
metamind-project-1772651663509
Generated by MetaMind - AI Pipeline Designer

A production-ready RAG (Retrieval-Augmented Generation) pipeline
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import uvicorn
import os

# LangChain imports
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.llms import ChatOpenAI
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate

# Initialize FastAPI app
app = FastAPI(
    title="metamind-project-1772651663509",
    description="RAG Pipeline powered by MetaMind",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
EMBEDDING_MODEL = "text-embedding-ada-002"
LLM_MODEL = "gpt-3.5-turbo"
VECTOR_DB_PATH = "./chroma_db"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

# Initialize components
print("🚀 Initializing RAG Pipeline...")

# Embeddings
embeddings = OpenAIEmbeddings(
    model_name=EMBEDDING_MODEL
)

# Vector store
vectorstore = Chroma(
    persist_directory=VECTOR_DB_PATH,
    embedding_function=embeddings
)

# LLM
llm = ChatOpenAI(
    
    model=LLM_MODEL,
    temperature=0.7
)

# Prompt template
prompt_template = """Use the following pieces of context to answer the question at the end. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.

Context: {context}

Question: {question}

Answer:"""

PROMPT = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)

# Create QA chain
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever(search_kwargs={"k": 3}),
    chain_type_kwargs={"prompt": PROMPT},
    return_source_documents=True
)

print("✅ RAG Pipeline initialized successfully!")


# Pydantic models
class QueryRequest(BaseModel):
    question: str
    top_k: Optional[int] = 3


class QueryResponse(BaseModel):
    answer: str
    sources: List[dict]
    confidence: float


class DocumentRequest(BaseModel):
    text: str
    metadata: Optional[dict] = {}


class HealthResponse(BaseModel):
    status: str
    model: str
    vector_db_size: int


# API endpoints
@app.get("/")
async def root():
    """Root endpoint with API information."""
    return {
        "name": "metamind-project-1772651663509",
        "type": "RAG Pipeline",
        "version": "1.0.0",
        "endpoints": {
            "query": "POST /query",
            "add_document": "POST /documents",
            "health": "GET /health"
        }
    }


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint."""
    try:
        # Get vector store size
        collection = vectorstore._collection
        count = collection.count()
        
        return HealthResponse(
            status="healthy",
            model=LLM_MODEL,
            vector_db_size=count
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Health check failed: {str(e)}")


@app.post("/query", response_model=QueryResponse)
async def query(request: QueryRequest):
    """
    Query the RAG pipeline with a question.
    
    The system will:
    1. Retrieve relevant documents from the vector store
    2. Generate an answer using the LLM with retrieved context
    3. Return the answer with source documents
    """
    try:
        # Run QA chain
        result = qa_chain({"query": request.question})
        
        # Extract answer and sources
        answer = result["result"]
        source_docs = result.get("source_documents", [])
        
        # Format sources
        sources = [
            {
                "content": doc.page_content[:200] + "..." if len(doc.page_content) > 200 else doc.page_content,
                "metadata": doc.metadata
            }
            for doc in source_docs
        ]
        
        # Calculate confidence (simple heuristic based on source relevance)
        confidence = min(len(source_docs) / request.top_k, 1.0) if source_docs else 0.0
        
        return QueryResponse(
            answer=answer,
            sources=sources,
            confidence=confidence
        )
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Query failed: {str(e)}")


@app.post("/documents")
async def add_document(request: DocumentRequest):
    """
    Add a new document to the vector store.
    
    The document will be:
    1. Split into chunks
    2. Embedded using the embedding model
    3. Stored in the vector database
    """
    try:
        # Split text into chunks
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP
        )
        chunks = text_splitter.split_text(request.text)
        
        # Add to vector store
        vectorstore.add_texts(
            texts=chunks,
            metadatas=[request.metadata] * len(chunks)
        )
        
        # Persist
        vectorstore.persist()
        
        return {
            "status": "success",
            "chunks_added": len(chunks),
            "message": f"Document added successfully with {len(chunks)} chunks"
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to add document: {str(e)}")


@app.delete("/documents")
async def clear_documents():
    """Clear all documents from the vector store."""
    try:
        # Delete collection
        vectorstore.delete_collection()
        
        # Recreate empty collection
        vectorstore._collection = vectorstore._client.create_collection(
            name=vectorstore._collection.name,
            embedding_function=embeddings
        )
        
        return {
            "status": "success",
            "message": "All documents cleared"
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear documents: {str(e)}")


if __name__ == "__main__":
    print(f"🚀 Starting metamind-project-1772651663509...")
    print(f"📍 API Documentation: http://localhost:8000/docs")
    print(f"📍 Health Check: http://localhost:8000/health")
    
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )