"""
metamind-project-1772694445932 - Healthcare Patient Monitoring System
Generated by MetaMind - AI Pipeline Designer

A production-ready real-time patient vital signs monitoring system
with anomaly detection and HIPAA compliance.
"""

import os
import logging
from datetime import datetime
from typing import List, Optional, Dict, Any
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, validator
import uvicorn
from sqlalchemy import create_engine, Column, Integer, Float, String, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session
import numpy as np
from sklearn.ensemble import IsolationForest
import redis
import json

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Database setup
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://user:password@localhost/healthcare_db")
engine = create_engine(DATABASE_URL, pool_pre_ping=True, pool_size=10, max_overflow=20)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Redis setup for caching and real-time alerts
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
redis_client = redis.from_url(REDIS_URL, decode_responses=True)

# ============================================================================
# Database Models
# ============================================================================

class Patient(Base):
    """Patient information model"""
    __tablename__ = "patients"
    
    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    age = Column(Integer)
    gender = Column(String)
    room_number = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    is_active = Column(Boolean, default=True)


class VitalSigns(Base):
    """Vital signs readings model"""
    __tablename__ = "vital_signs"
    
    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(String, index=True, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    heart_rate = Column(Float)
    blood_pressure_systolic = Column(Float)
    blood_pressure_diastolic = Column(Float)
    oxygen_saturation = Column(Float)
    temperature = Column(Float)
    respiratory_rate = Column(Float)
    anomaly_score = Column(Float)
    is_anomaly = Column(Boolean, default=False)


class Alert(Base):
    """Alert notifications model"""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(String, index=True, nullable=False)
    alert_type = Column(String)  # critical, warning, info
    message = Column(String)
    vital_signs_id = Column(Integer)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    acknowledged = Column(Boolean, default=False)
    acknowledged_by = Column(String, nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)


# Create tables
Base.metadata.create_all(bind=engine)

# ============================================================================
# Pydantic Models
# ============================================================================

class VitalSignsInput(BaseModel):
    """Input model for vital signs data"""
    patient_id: str = Field(..., description="Unique patient identifier")
    heart_rate: float = Field(..., ge=0, le=300, description="Heart rate in BPM")
    blood_pressure_systolic: float = Field(..., ge=0, le=300, description="Systolic BP in mmHg")
    blood_pressure_diastolic: float = Field(..., ge=0, le=200, description="Diastolic BP in mmHg")
    oxygen_saturation: float = Field(..., ge=0, le=100, description="SpO2 percentage")
    temperature: float = Field(..., ge=90, le=110, description="Temperature in Fahrenheit")
    respiratory_rate: float = Field(..., ge=0, le=60, description="Breaths per minute")
    
    @validator('blood_pressure_systolic')
    def validate_bp_systolic(cls, v, values):
        if 'blood_pressure_diastolic' in values and v < values['blood_pressure_diastolic']:
            raise ValueError('Systolic BP must be greater than diastolic BP')
        return v


class VitalSignsResponse(BaseModel):
    """Response model for vital signs"""
    id: int
    patient_id: str
    timestamp: datetime
    heart_rate: float
    blood_pressure_systolic: float
    blood_pressure_diastolic: float
    oxygen_saturation: float
    temperature: float
    respiratory_rate: float
    anomaly_score: float
    is_anomaly: bool
    
    class Config:
        orm_mode = True


class AlertResponse(BaseModel):
    """Response model for alerts"""
    id: int
    patient_id: str
    alert_type: str
    message: str
    timestamp: datetime
    acknowledged: bool
    
    class Config:
        orm_mode = True


class PatientResponse(BaseModel):
    """Response model for patient"""
    id: int
    patient_id: str
    name: str
    age: Optional[int]
    gender: Optional[str]
    room_number: Optional[str]
    is_active: bool
    
    class Config:
        orm_mode = True


class HealthCheck(BaseModel):
    """Health check response"""
    status: str
    timestamp: datetime
    database: str
    redis: str
    ml_model: str


# ============================================================================
# ML Model - Anomaly Detection
# ============================================================================

class AnomalyDetector:
    """Isolation Forest based anomaly detector for vital signs"""
    
    def __init__(self):
        self.model = IsolationForest(
            contamination=0.1,
            random_state=42,
            n_estimators=100
        )
        self.is_trained = False
        self.feature_names = [
            'heart_rate', 'blood_pressure_systolic', 'blood_pressure_diastolic',
            'oxygen_saturation', 'temperature', 'respiratory_rate'
        ]
        logger.info("Anomaly detector initialized")
    
    def extract_features(self, vital_signs: VitalSignsInput) -> np.ndarray:
        """Extract features from vital signs"""
        return np.array([[
            vital_signs.heart_rate,
            vital_signs.blood_pressure_systolic,
            vital_signs.blood_pressure_diastolic,
            vital_signs.oxygen_saturation,
            vital_signs.temperature,
            vital_signs.respiratory_rate
        ]])
    
    def train(self, historical_data: List[VitalSignsInput]):
        """Train the model on historical data"""
        if len(historical_data) < 100:
            logger.warning(f"Insufficient training data: {len(historical_data)} samples")
            return
        
        features = np.vstack([self.extract_features(vs) for vs in historical_data])
        self.model.fit(features)
        self.is_trained = True
        logger.info(f"Model trained on {len(historical_data)} samples")
    
    def predict(self, vital_signs: VitalSignsInput) -> tuple[float, bool]:
        """
        Predict anomaly score and classification
        Returns: (anomaly_score, is_anomaly)
        """
        features = self.extract_features(vital_signs)
        
        if not self.is_trained:
            # Use rule-based detection if model not trained
            return self._rule_based_detection(vital_signs)
        
        # Get anomaly score (-1 for anomaly, 1 for normal)
        prediction = self.model.predict(features)[0]
        score = self.model.score_samples(features)[0]
        
        # Convert to 0-1 scale (higher = more anomalous)
        anomaly_score = float(1 / (1 + np.exp(score)))
        is_anomaly = prediction == -1
        
        return anomaly_score, is_anomaly
    
    def _rule_based_detection(self, vital_signs: VitalSignsInput) -> tuple[float, bool]:
        """Rule-based anomaly detection as fallback"""
        anomalies = 0
        total_checks = 6
        
        # Check each vital sign against normal ranges
        if not (60 <= vital_signs.heart_rate <= 100):
            anomalies += 1
        if not (90 <= vital_signs.blood_pressure_systolic <= 140):
            anomalies += 1
        if not (60 <= vital_signs.blood_pressure_diastolic <= 90):
            anomalies += 1
        if not (95 <= vital_signs.oxygen_saturation <= 100):
            anomalies += 1
        if not (97 <= vital_signs.temperature <= 99):
            anomalies += 1
        if not (12 <= vital_signs.respiratory_rate <= 20):
            anomalies += 1
        
        anomaly_score = anomalies / total_checks
        is_anomaly = anomaly_score > 0.3
        
        return anomaly_score, is_anomaly


# Initialize ML model
anomaly_detector = AnomalyDetector()

# ============================================================================
# WebSocket Connection Manager
# ============================================================================

class ConnectionManager:
    """Manage WebSocket connections for real-time updates"""
    
    def __init__(self):
        self.active_connections: Dict[str, List[WebSocket]] = {}
    
    async def connect(self, websocket: WebSocket, patient_id: str):
        await websocket.accept()
        if patient_id not in self.active_connections:
            self.active_connections[patient_id] = []
        self.active_connections[patient_id].append(websocket)
        logger.info(f"WebSocket connected for patient {patient_id}")
    
    def disconnect(self, websocket: WebSocket, patient_id: str):
        if patient_id in self.active_connections:
            self.active_connections[patient_id].remove(websocket)
            if not self.active_connections[patient_id]:
                del self.active_connections[patient_id]
        logger.info(f"WebSocket disconnected for patient {patient_id}")
    
    async def broadcast_to_patient(self, patient_id: str, message: dict):
        """Send message to all connections for a specific patient"""
        if patient_id in self.active_connections:
            for connection in self.active_connections[patient_id]:
                try:
                    await connection.send_json(message)
                except Exception as e:
                    logger.error(f"Error broadcasting to patient {patient_id}: {e}")
    
    async def broadcast_alert(self, alert: Alert):
        """Broadcast alert to all relevant connections"""
        message = {
            "type": "alert",
            "patient_id": alert.patient_id,
            "alert_type": alert.alert_type,
            "message": alert.message,
            "timestamp": alert.timestamp.isoformat()
        }
        await self.broadcast_to_patient(alert.patient_id, message)


manager = ConnectionManager()

# ============================================================================
# Database Dependency
# ============================================================================

def get_db():
    """Database session dependency"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ============================================================================
# FastAPI Application
# ============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown events"""
    logger.info("🚀 Starting Healthcare Patient Monitoring System...")
    logger.info(f"Database: {DATABASE_URL}")
    logger.info(f"Redis: {REDIS_URL}")
    yield
    logger.info("Shutting down Healthcare Patient Monitoring System...")


app = FastAPI(
    title="metamind-project-1772694445932",
    description="Production-ready Healthcare Patient Monitoring System with Real-time Anomaly Detection",
    version="1.0.0",
    lifespan=lifespan
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================================
# API Endpoints
# ============================================================================

@app.get("/health", response_model=HealthCheck)
async def health_check(db: Session = Depends(get_db)):
    """Health check endpoint"""
    try:
        # Check database
        db.execute("SELECT 1")
        db_status = "healthy"
    except Exception as e:
        logger.error(f"Database health check failed: {e}")
        db_status = "unhealthy"
    
    try:
        # Check Redis
        redis_client.ping()
        redis_status = "healthy"
    except Exception as e:
        logger.error(f"Redis health check failed: {e}")
        redis_status = "unhealthy"
    
    ml_status = "trained" if anomaly_detector.is_trained else "untrained"
    
    overall_status = "healthy" if db_status == "healthy" and redis_status == "healthy" else "degraded"
    
    return HealthCheck(
        status=overall_status,
        timestamp=datetime.utcnow(),
        database=db_status,
        redis=redis_status,
        ml_model=ml_status
    )


@app.post("/api/vital-signs", response_model=VitalSignsResponse, status_code=status.HTTP_201_CREATED)
async def record_vital_signs(
    vital_signs: VitalSignsInput,
    db: Session = Depends(get_db)
):
    """
    Record patient vital signs and detect anomalies
    
    This endpoint:
    1. Validates vital signs data
    2. Runs anomaly detection
    3. Stores data in database
    4. Generates alerts if anomalies detected
    5. Broadcasts real-time updates via WebSocket
    """
    try:
        # Run anomaly detection
        anomaly_score, is_anomaly = anomaly_detector.predict(vital_signs)
        
        # Create database record
        db_vital_signs = VitalSigns(
            patient_id=vital_signs.patient_id,
            heart_rate=vital_signs.heart_rate,
            blood_pressure_systolic=vital_signs.blood_pressure_systolic,
            blood_pressure_diastolic=vital_signs.blood_pressure_diastolic,
            oxygen_saturation=vital_signs.oxygen_saturation,
            temperature=vital_signs.temperature,
            respiratory_rate=vital_signs.respiratory_rate,
            anomaly_score=anomaly_score,
            is_anomaly=is_anomaly
        )
        
        db.add(db_vital_signs)
        db.commit()
        db.refresh(db_vital_signs)
        
        # Cache latest vital signs in Redis
        redis_key = f"patient:{vital_signs.patient_id}:latest"
        redis_client.setex(
            redis_key,
            300,  # 5 minutes TTL
            json.dumps({
                "heart_rate": vital_signs.heart_rate,
                "blood_pressure": f"{vital_signs.blood_pressure_systolic}/{vital_signs.blood_pressure_diastolic}",
                "oxygen_saturation": vital_signs.oxygen_saturation,
                "temperature": vital_signs.temperature,
                "respiratory_rate": vital_signs.respiratory_rate,
                "anomaly_score": anomaly_score,
                "is_anomaly": is_anomaly,
                "timestamp": datetime.utcnow().isoformat()
            })
        )
        
        # Generate alert if anomaly detected
        if is_anomaly:
            alert_type = "critical" if anomaly_score > 0.7 else "warning"
            alert_message = f"Anomaly detected in vital signs (score: {anomaly_score:.2f})"
            
            alert = Alert(
                patient_id=vital_signs.patient_id,
                alert_type=alert_type,
                message=alert_message,
                vital_signs_id=db_vital_signs.id
            )
            db.add(alert)
            db.commit()
            
            # Broadcast alert via WebSocket
            await manager.broadcast_alert(alert)
            
            logger.warning(f"Anomaly detected for patient {vital_signs.patient_id}: {alert_message}")
        
        # Broadcast vital signs update
        await manager.broadcast_to_patient(
            vital_signs.patient_id,
            {
                "type": "vital_signs",
                "data": {
                    "heart_rate": vital_signs.heart_rate,
                    "blood_pressure": f"{vital_signs.blood_pressure_systolic}/{vital_signs.blood_pressure_diastolic}",
                    "oxygen_saturation": vital_signs.oxygen_saturation,
                    "temperature": vital_signs.temperature,
                    "respiratory_rate": vital_signs.respiratory_rate,
                    "anomaly_score": anomaly_score,
                    "is_anomaly": is_anomaly,
                    "timestamp": db_vital_signs.timestamp.isoformat()
                }
            }
        )
        
        logger.info(f"Recorded vital signs for patient {vital_signs.patient_id}")
        return db_vital_signs
        
    except Exception as e:
        logger.error(f"Error recording vital signs: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to record vital signs: {str(e)}")


@app.get("/api/patients/{patient_id}/vital-signs", response_model=List[VitalSignsResponse])
async def get_patient_vital_signs(
    patient_id: str,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """Get vital signs history for a patient"""
    vital_signs = db.query(VitalSigns).filter(
        VitalSigns.patient_id == patient_id
    ).order_by(VitalSigns.timestamp.desc()).limit(limit).all()
    
    return vital_signs


@app.get("/api/patients/{patient_id}/alerts", response_model=List[AlertResponse])
async def get_patient_alerts(
    patient_id: str,
    acknowledged: Optional[bool] = None,
    db: Session = Depends(get_db)
):
    """Get alerts for a patient"""
    query = db.query(Alert).filter(Alert.patient_id == patient_id)
    
    if acknowledged is not None:
        query = query.filter(Alert.acknowledged == acknowledged)
    
    alerts = query.order_by(Alert.timestamp.desc()).all()
    return alerts


@app.post("/api/alerts/{alert_id}/acknowledge")
async def acknowledge_alert(
    alert_id: int,
    acknowledged_by: str,
    db: Session = Depends(get_db)
):
    """Acknowledge an alert"""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    alert.acknowledged = True
    alert.acknowledged_by = acknowledged_by
    alert.acknowledged_at = datetime.utcnow()
    
    db.commit()
    
    logger.info(f"Alert {alert_id} acknowledged by {acknowledged_by}")
    return {"message": "Alert acknowledged successfully"}


@app.websocket("/ws/{patient_id}")
async def websocket_endpoint(websocket: WebSocket, patient_id: str):
    """WebSocket endpoint for real-time updates"""
    await manager.connect(websocket, patient_id)
    try:
        while True:
            # Keep connection alive
            data = await websocket.receive_text()
            # Echo back for heartbeat
            await websocket.send_json({"type": "heartbeat", "timestamp": datetime.utcnow().isoformat()})
    except WebSocketDisconnect:
        manager.disconnect(websocket, patient_id)


# ============================================================================
# Main
# ============================================================================

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )